FROM python:3.10-slim

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar archivos al contenedor
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer puerto 3000
EXPOSE 3000

# Ejecutar la app
CMD ["python", "app.py"]
